using Granny.Core;
using Granny.Gameplay.Player;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace Granny.Tests
{
    /// <summary>
    /// The player rig is generated by PlayerRigBuilder and is easy to break by
    /// dragging things around in the Hierarchy. These assertions pin the parts of
    /// the structure that other systems depend on.
    /// </summary>
    public class PlayerRigTests
    {
        const string PrefabPath = "Assets/_Project/Prefabs/Player.prefab";

        static GameObject LoadPrefab()
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(PrefabPath);
            Assert.IsNotNull(prefab, $"No player prefab at {PrefabPath}. Run Granny > Build Player Rig.");
            return prefab;
        }

        [Test]
        public void PrefabHasTheExpectedComponents()
        {
            var prefab = LoadPrefab();

            Assert.IsNotNull(prefab.GetComponent<CharacterController>());
            Assert.IsNotNull(prefab.GetComponent<PlayerInputReader>());
            Assert.IsNotNull(prefab.GetComponent<PlayerMotor>());
            Assert.IsNotNull(prefab.GetComponent<PlayerLook>());
            Assert.IsNotNull(prefab.GetComponent<HeadBob>());
            Assert.IsNotNull(prefab.GetComponentInChildren<PlayerFlashlight>(includeInactive: true));
        }

        [Test]
        public void PlayerIsOnThePlayerLayer()
        {
            Assert.AreEqual(GameLayers.Player, LoadPrefab().layer);
        }

        [Test]
        public void ExactlyOneCameraAndOneAudioListener()
        {
            var prefab = LoadPrefab();
            Assert.AreEqual(1, prefab.GetComponentsInChildren<Camera>(true).Length);
            Assert.AreEqual(1, prefab.GetComponentsInChildren<AudioListener>(true).Length);
        }

        [Test]
        public void BobTargetIsBelowTheCameraPivot()
        {
            // PlayerMotor drives the pivot's height for crouching and HeadBob
            // offsets the bob target. If they were the same transform, crouching
            // and bobbing would overwrite each other every frame.
            var prefab = LoadPrefab();

            var pivot = prefab.transform.Find("CameraPivot");
            Assert.IsNotNull(pivot, "Expected a 'CameraPivot' child.");

            var bobTarget = pivot.Find("BobTarget");
            Assert.IsNotNull(bobTarget, "Expected 'BobTarget' under 'CameraPivot'.");
            Assert.AreNotSame(pivot, bobTarget);

            var camera = prefab.GetComponentInChildren<Camera>(true);
            Assert.AreSame(bobTarget, camera.transform.parent, "Camera must hang off the bob target.");
        }

        [Test]
        public void FlashlightIsASpotLightAndStartsOff()
        {
            var torch = LoadPrefab().GetComponentInChildren<PlayerFlashlight>(true);
            var beam = torch.GetComponent<Light>();

            Assert.IsNotNull(beam, "The flashlight component needs a Light on the same object.");
            Assert.AreEqual(LightType.Spot, beam.type);
            Assert.IsFalse(beam.enabled, "The torch must start off; darkness is the default.");
        }

        [Test]
        public void SerializedReferencesAreWired()
        {
            var prefab = LoadPrefab();

            AssertWired(prefab.GetComponent<PlayerInputReader>(), "actions");
            AssertWired(prefab.GetComponent<PlayerMotor>(), "input");
            AssertWired(prefab.GetComponent<PlayerMotor>(), "cameraPivot");
            AssertWired(prefab.GetComponent<PlayerLook>(), "cameraPivot");
            AssertWired(prefab.GetComponent<HeadBob>(), "bobTarget");
            AssertWired(prefab.GetComponentInChildren<PlayerFlashlight>(true), "beam");
        }

        static void AssertWired(Object component, string fieldName)
        {
            var prop = new SerializedObject(component).FindProperty(fieldName);
            Assert.IsNotNull(prop, $"{component.GetType().Name} has no field '{fieldName}'.");
            Assert.IsNotNull(
                prop.objectReferenceValue,
                $"{component.GetType().Name}.{fieldName} is unassigned.");
        }
    }
}
